services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      BOT_SECRET: ${BOT_SECRET:-change_me_bot_secret}
      BOT_URL: http://bot:6000

  bot:
    build: ./bot
    environment:
      WEB_URL: http://web:5000
      BOT_SECRET: ${BOT_SECRET:-change_me_bot_secret}
      FLAG: exploiitm{H0P3_Cl4uD3_D1D_N0t_s0Lv3_1t}
      BOT_PORT: "6000"
